apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: htpwo7vht-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: htpwo7vht-go 
  name: htpwo7vht-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: htpwo7vht-go 
